





# Chapter3_Grid World
모두의 연구소 flipped school - advanced reinforcement learning 의 교재인 
Sutton Reinforcement Learning 책에 나오는 Chapter3. 밴딧 문제

코드는 


----

2016 Shangtong Zhang(zhangshangtong.cpp@gmail.com)                  
2016 Kenta Shimada(hyperkentakun@gmail.com)  

---
의 코드를 참고하였습니다

### Environment

넘파이의 함수를 통해 표준분포 랜덤값을 생성하고 인수로 받는 수보다 크면 1을 작으면 -1을 받는 함수를 만듭니다.

In [1]:
import numpy as np

### 5 * 5 짜리 그리드월드를 만들어 줍니다

In [45]:
height,weight=5,5
A_POS=[0,1]

A_PRIME_POS=[4,1]
B_POS=[0,3]
B_PIRME_POS=[2,3]
discount=0.9
world=np.zeros((height,weight))

###  action 설정

그리드월드에서 할수있는 action 으로 위,아래,오른쪽,왼쪽을 설정해줍니다.

In [3]:
actions=["L","R","D","U"]

Default 값으로 각 그리드에서 각 엑션을 선택할 확률을 25%로 설정합니다.

In [4]:
actionProb=[]

In [5]:
for i in range(0, 5):
    actionProb.append([])
    for j in range(0, 5):
        actionProb[i].append(dict({'L':0.25, 'U':0.25, 'R':0.25, 'D':0.25}))

In [6]:
actionProb

[[{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 

###  Next State

각 밴딧 문제와 다르게 그리드월드에서는 각 스테이트에서 어떠한 엑션을 선택했냐에 따라 다음의 스테이트가 변합니다.
각 스테이트에서 엑션을 선택했을때 받는 다음 스테이트를 정의해줍니다.

In [7]:
nextState=[]

###  Reward

마찬가지로 각 스테이트에서의 엑션 선택에 따라 받는 리워드도 달라집니다.


In [8]:
actionReward=[]

In [9]:
for i in range(0,5):
    nextState.append([])
    actionReward.append([])
   
    for j in range(0,5):
        next=dict()
        reward=dict()
        # 만약 0,0에 있을때 엑션이 윗방향이라면 그 자리에서 움직이지 않고 리워드는 -1을 받는다
        #참고 i는 row ,j는 column
        if i ==0:
           
            next['U'] = [i,j]
            
            reward['U'] = -1.0
            
        else:
            next['U']=[i-1,j]
            reward['U']=0.0
        if i==4:
            next['D']=[i,j]
            reward['D']=-1.0
        
        else:
            next['D']=[i+1,j]
            reward['D']=0.0
        if j==0:
            next['L']=[i,j]
            reward['L']=-0.1
        else:
            next['L']=[i,j-1]
            reward['L']=0.0
        if j==4:
            next['R']=[i,j]
            reward['R']=-0.1
        else:
            next['R']=[i,j+1]
            reward['R']=0.0
        if [i,j]==A_POS:
            next['L'] = next['R'] = next['D'] = next['U'] = A_PRIME_POS 
            reward['L'] = reward['R'] = reward['D'] = reward['U'] = 5.0
            
        nextState[i].append(next)
        actionReward[i].append(reward)
        


In [10]:
next

{'D': [4, 4], 'L': [4, 3], 'R': [4, 4], 'U': [3, 4]}

In [11]:
reward

{'D': -1.0, 'L': 0.0, 'R': -0.1, 'U': 0.0}

#### Example of using dict()

In [35]:
a=dict()

a['a']=[5,2]
a

{'a': [5, 2]}

## Policy iteration

벨만방정식으로 업데이트를 하면서 월드와 업데이트한 뉴월드의 오차가 매우 작으면 멈춘다! 

In [51]:


while True:
    #until convergence
    newWorld=np.zeros((5,5))
    somany+=1
    for i in range(0,5):
        for j in range(0,5):
            for action in actions:
                newPosition=nextState[i][j][action]
                #bellman
         
                newWorld[i, j] += actionProb[i][j][action] * (actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
                
    if np.sum(np.abs(world-newWorld))<1e-4:
        
    

        print(newWorld)
        break
    world=newWorld

[[ 1.46159439  4.01167018  0.86462721 -0.35305208 -0.82570799]
 [ 0.78332305  1.2217614   0.43063814 -0.14389164 -0.44313827]
 [ 0.1258528   0.20440403 -0.02856495 -0.27398145 -0.44566969]
 [-0.44313827 -0.41060213 -0.48803134 -0.59958433 -0.70686891]
 [-1.13051998 -1.09814806 -1.13029202 -1.19595281 -1.27842082]]


## Q value iteration

In [52]:
world=np.zeros((5,5))
while True:
    newWorld=np.zeros((5,5))
    for i in range(0,5):
        for j in range(0,5):
            values=[]
            for action in actions:
                newPosition=nextState[i][j][action]
                #value iteration
                values.append(actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
            newWorld[i][j] =np.max(values)
    if np.sum(np.abs(world-newWorld))<1e-4:
  
        print(newWorld)
        break
    world=newWorld
                

[[ 10.98870716  12.20967462  10.98870716   9.88983644   8.9008528 ]
 [  9.88983644  10.98870716   9.88983644   8.9008528    8.01074958]
 [  8.9008528    9.88983644   8.9008528    8.01074958   7.20967462]
 [  8.01074958   8.9008528    8.01074958   7.20967462   6.48870716]
 [  7.20967462   8.01074958   7.20967462   6.48870716   5.83983644]]
